/* eslint-disable @typescript-eslint/no-explicit-any */
export class InvoiceData {
  accountCode: string;
  actionable: string;
  address: string;
  agingBucket: string;
  agingInvoiceDate: string;
  agingReport: string;
  bun: string;
  billTo: string;
  billToAlt: string;
  billingInformation: string;
  business: string;
  businessFooter: string;
  businessUnit: string;
  cpc: string;
  campaignId: string;
  client: string;
  company: string;
  companyInformation: string;
  companyInfo: string;
  currency: string;
  definition: string;
  discrepancies: string;
  discrepancyReason: string;
  division: string;
  documentReference: string;
  fileInfo: string;
  financialDetails: string;
  financialSummary: string;
  firstEmailSendDate: string;
  hstGst: string;
  invoice: string;
  invoiceDetails: string;
  invoiceInformation: string;
  invoiceAmount: number;
  invoiceDate: string;
  invoiceDue: string;
  invoiceNo: string;
  invoiceNumber: string;
  invoiceTitle: string;
  issue: string;
  issueDetails: string;
  lastUpdated: string;
  mo: string;
  mediaType: string;
  po: string;
  pageInfo: string;
  payToVendorName: string;
  qst: string;
  reconciliationNotes: string;
  reportDate: string;
  representative: string;
  resolutionEmailId: string;
  spoc: string;
  sessionId: string;
  status: string;
  subsidiaryVendorName: string;
  summary: string;
  telephone: string;
  terms: string;
  timestamp: string;
  vendorName: string;
  violations: string;
  year: string;
  billingAddress: string;
  businessDetails: string;
  companyContact: string;
  metadata: string;
  output: string;
  rowData: string;
  rowNumber: number;
  toolCallId: string;

  constructor(data?: any) {
    this.accountCode = data?.["Account_Code"] || "";
    this.actionable = data?.["Actionable"] || "";
    this.address = data?.["Address"] || "";
    this.agingBucket = data?.["Aging_Bucket"] || "";
    this.agingInvoiceDate = data?.["Aging_Invoice_Date"] || "";
    this.agingReport = data?.["Aging_Report"] || "";
    this.bun = data?.["BUN"] || "";
    this.billTo = data?.["BillTo"] || "";
    this.billToAlt = data?.["Bill_To"] || "";
    this.billingInformation = data?.["Billing Information"] || "";
    this.business = data?.["Business"] || "";
    this.businessFooter = data?.["BusinessFooter"] || "";
    this.businessUnit = data?.["Business_Unit"] || "";
    this.cpc = data?.["CPC"] || "";
    this.campaignId = data?.["Campaign_ID"] || "";
    this.client = data?.["Client"] || "";
    this.company = data?.["Company"] || "";
    this.companyInformation = data?.["Company Information"] || "";
    this.companyInfo = data?.["Company_Info"] || "";
    this.currency = data?.["Currency"] || "";
    this.definition = data?.["Definition"] || "";
    this.discrepancies = data?.["Discrepancies"] || "";
    this.discrepancyReason = data?.["Discrepancy_Reason"] || "";
    this.division = data?.["Division"] || "";
    this.documentReference = data?.["Document Reference"] || "";
    this.fileInfo = data?.["File_Info"] || "";
    this.financialDetails = data?.["Financial Details"] || "";
    this.financialSummary = data?.["FinancialSummary"] || "";
    this.firstEmailSendDate = data?.["First_Email_Send_Date"] || "";
    this.hstGst = data?.["HST/GST"] || "";
    this.invoice = data?.["Invoice"] || "";
    this.invoiceDetails = data?.["Invoice Details"] || "";
    this.invoiceInformation = data?.["Invoice Information"] || "";
    this.invoiceAmount = data?.["Invoice_Amount"] || 0;
    this.invoiceDate = data?.["Invoice_Date"] || "";
    this.invoiceDue = data?.["Invoice_Due"] || "";
    this.invoiceNo = data?.["Invoice_No"] || "";
    this.invoiceNumber = data?.["Invoice_Number"] || "";
    this.invoiceTitle = data?.["Invoice_Title"] || "";
    this.issue = data?.["Issue"] || "";
    this.issueDetails = data?.["Issue Details"] || "";
    this.lastUpdated = data?.["Last_Updated"] || "";
    this.mo = data?.["MO"] || "";
    this.mediaType = data?.["Media_Type"] || "";
    this.po = data?.["P.O."] || "";
    this.pageInfo = data?.["PageInfo"] || "";
    this.payToVendorName = data?.["Pay_To_Vendor_Name"] || "";
    this.qst = data?.["QST"] || "";
    this.reconciliationNotes = data?.["Reconciliation_Notes"] || "";
    this.reportDate = data?.["Report_Date"] || "";
    this.representative = data?.["Representative"] || "";
    this.resolutionEmailId = data?.["Resolution_Email_Id"] || "";
    this.spoc = data?.["SPOC"] || "";
    this.sessionId = data?.["Session_ID"] || "";
    this.status = data?.["Status"] || "";
    this.subsidiaryVendorName = data?.["Subsidiary_Vendor_Name"] || "";
    this.summary = data?.["Summary"] || "";
    this.telephone = data?.["Telephone"] || "";
    this.terms = data?.["Terms"] || "";
    this.timestamp = data?.["Timestamp"] || "";
    this.vendorName = data?.["Vendor_Name"] || "";
    this.violations = data?.["Violations"] || "";
    this.year = data?.["Year"] || "";
    this.billingAddress = data?.["billing_address"] || "";
    this.businessDetails = data?.["business_details"] || "";
    this.companyContact = data?.["company_contact"] || "";
    this.metadata = data?.["metadata"] || "";
    this.output = data?.["output"] || "";
    this.rowData = data?.["row_data"] || "";
    this.rowNumber = data?.["row_number"] || 0;
    this.toolCallId = data?.["toolCallId"] || "";
  }
}
